// action types
export default {
	GIT_REQUEST: 'GIT_REQUEST',
	GIT_CALL_SUCCESS: 'GIT_CALL_SUCCESS',
	GIT_CALL_FAILURE: 'GIT_CALL_FAILURE',
	MEDIUM_REQUEST: 'MEDIUM_REQUEST',
	MEDIUM_CALL_SUCCESS: 'MEDIUM_CALL_SUCCESS',
	MEDIUM_CALL_FAILURE: 'MEDIUM_CALL_FAILURE',
	CHANGE_ACTIVE_TAB: 'CHANGE_ACTIVE_TAB',
	NEXT_GIT_DATA: 'NEXT_GIT_DATA',
	NEXT_MEDIUM_DATA: 'NEXT_MEDIUM_DATA',
	RESULT_NEXT_GIT_DATA: 'RESULT_NEXT_GIT_DATA',
	RESULT_NEXT_MEDIUM_DATA: 'RESULT_NEXT_MEDIUM_DATA',
};